# Generated by Django 4.0.10 on 2025-06-17 11:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('video', models.URLField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('published_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
